CREATE TABLE IF NOT EXISTS LANDAHOY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TVDB_ID INTEGER,
    COMPLETE BOOLEAN,
    LAST_MOD INTEGER,
    IGNORE BOOLEAN,
    JUSTIFICATION TEXT,
    UNIQUE(TVDB_ID)
);